<x-layouts.app title="Kelola Pencairan Saldo Guru">
    @php
        $tabs = ['pending' => 'Menunggu', 'approved' => 'Diproses', 'paid' => 'Selesai', 'rejected' => 'Ditolak'];
        $statusStyle = ['pending' => 'bg-amber-50 text-amber-700 ring-amber-100', 'approved' => 'bg-sky-50 text-sky-700 ring-sky-100', 'paid' => 'bg-emerald-50 text-emerald-700 ring-emerald-100', 'rejected' => 'bg-rose-50 text-rose-700 ring-rose-100'];
    @endphp

    <div class="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
        <div><nav aria-label="Breadcrumb" class="mb-4 flex items-center gap-2 text-xs text-ink-muted"><a href="{{ route('admin.dashboard') }}" class="hover:text-board">Panel Admin</a><span aria-hidden="true">›</span><span class="text-ink">Kelola Pencairan Saldo Guru</span></nav><h1 class="font-display text-3xl font-bold tracking-tight text-ink">Kelola Pencairan Saldo Guru</h1><p class="mt-2 text-sm text-ink-muted">Tinjau permintaan pencairan saldo dari para guru.</p></div>
        <div class="flex min-w-[180px] items-center gap-3 rounded-xl border border-line bg-white px-4 py-3 shadow-sm"><span class="grid h-10 w-10 place-items-center rounded-xl bg-chalk/30 text-success"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 21h18M5 21V9l7-5 7 5v12"/></svg></span><div><p class="text-xs text-ink-muted">Menunggu persetujuan</p><p class="text-2xl font-extrabold text-ink">{{ $statusCounts['pending'] ?? 0 }}</p></div></div>
    </div>

    <section class="overflow-hidden rounded-2xl border border-line bg-white shadow-sm">
        <div class="overflow-x-auto border-b border-line"><nav class="flex min-w-max gap-1 px-4" aria-label="Status pencairan">@foreach($tabs as $tabStatus => $tabLabel)<a href="{{ route('admin.payouts', array_filter(['status' => $tabStatus, 'search' => request('search')])) }}" @class(['border-b-2 px-4 py-4 text-sm font-bold', 'border-board text-board' => $status === $tabStatus, 'border-transparent text-ink-muted hover:text-board' => $status !== $tabStatus])>{{ $tabLabel }} <span @class(['ml-2 rounded-full px-2 py-0.5 text-xs', 'bg-chalk/30 text-success' => $tabStatus !== 'rejected', 'bg-rose-100 text-rose-700' => $tabStatus === 'rejected'])>{{ $statusCounts[$tabStatus] ?? 0 }}</span></a>@endforeach</nav></div>
        <form method="GET" action="{{ route('admin.payouts') }}" class="flex flex-col gap-3 border-b border-line bg-paper/60 p-4 sm:flex-row"><input type="hidden" name="status" value="{{ $status }}"><label class="relative flex-1"><span class="sr-only">Cari guru</span><svg class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-muted" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input type="search" name="search" value="{{ request('search') }}" placeholder="Cari nama guru..." class="w-full rounded-lg border-line bg-white py-2.5 pl-10 pr-3 text-sm text-ink placeholder:text-ink-muted focus:border-board focus:ring-board"></label><button type="submit" class="inline-flex items-center justify-center gap-2 rounded-lg border border-board bg-white px-4 py-2.5 text-sm font-bold text-board hover:bg-board hover:text-white"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 5h16l-6 7v5l-4 2v-7L4 5Z"/></svg>Filter</button></form>

        <div class="divide-y divide-line">
            @forelse($payouts as $payout)
                <article class="p-4 sm:p-5"><div class="flex flex-col gap-4 md:flex-row md:items-center"><div class="flex min-w-0 flex-1 items-center gap-3"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-board/10 text-sm font-bold text-board">{{ strtoupper(substr($payout->tutor->user->name, 0, 2)) }}</span><div class="min-w-0"><p class="truncate text-sm font-bold text-ink">{{ $payout->tutor->user->name }}</p><p class="mt-1 truncate text-xs text-ink-muted">{{ $payout->bank_name }} · {{ $payout->account_number }} · a.n. {{ $payout->account_holder }}</p></div></div><div class="md:w-48"><p class="text-base font-extrabold text-board">Rp{{ number_format($payout->amount, 0, ',', '.') }}</p><p class="mt-1 text-xs text-ink-muted">Diajukan {{ $payout->created_at->translatedFormat('d M Y, H:i') }}</p></div><div class="flex items-center gap-3 md:w-48 md:justify-end"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold ring-1 ring-inset {{ $statusStyle[$payout->status] }}">{{ $tabs[$payout->status] }}</span>@if($payout->status === 'pending')<div class="flex gap-2"><form method="POST" action="{{ route('admin.payouts.reject', $payout) }}" onsubmit="return confirm('Tolak pengajuan ini?')">@csrf<button class="rounded-lg border border-rose-300 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50">Tolak</button></form><form method="POST" action="{{ route('admin.payouts.approve', $payout) }}" onsubmit="return confirm('Sudah mentransfer dana ke guru?')">@csrf<button class="rounded-lg bg-board px-3 py-2 text-xs font-bold text-white hover:bg-board-light">Setujui</button></form></div>@endif</div></div></article>
            @empty
                <p class="px-5 py-14 text-center text-sm text-ink-muted">Tidak ada permintaan pencairan dengan status ini.</p>
            @endforelse
        </div>
        @if($payouts->hasPages())<div class="border-t border-line px-5 py-4">{{ $payouts->links() }}</div>@endif
    </section>
</x-layouts.app>
